### PR TITLE
Feature/milestone2

### PR DESCRIPTION
**Pull request by epinczinger**
I've merged the first milestone/branch because I had it approved since I started with a partner that had to leave for personal issues.

On this branch, I do the following actions:

- Add friendship model and controller.
- Add Associations between users and friendship.
- Corresponding methods to make it works.

I follow the given instructions on the project, including [this](https://explainextended.com/2009/03/07/selecting-friends/)  tutorial

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @epinczinger 
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] Add unit and integration tests as it is a requirement
- [x] Add Accept and Reject button upon a user sends a friend invitation request
### Make the changes and submit for another code review. Good luck!
- Happy coding!

**Comment by epinczinger** [comment]
Hi @rOluochKe, thanks for your review!

Requested changes have been done.
Submitting for another review.

**Review by adaorachi — CHANGES_REQUESTED** [review]
### Hi @epinczinger :wave: 
You've done a good job implementing the changes requested in the previous review. Well done! :+1: 
However, there are still some minor fixes you need to do on them.

---

### STATUS: CHANGES REQUIRED :recycle: 

---

- [x] There is a button to invite the user to friendship on the users' list page and on the single-user page.
You already have the button on the **users' list page**. Kindly implement it on the **single-user page** as well. Here is a [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from pathwright in that regard.

- [x] The posts timeline should include posts written by logged-in user and their friends but this is not properly implemented in your project. A user can see all posts written by all users whether they are friends with them or not. Kindly ensure this is fixed. Here is a [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from pathwright for clarification.

- [x] You do not have Github action configured in your repo and that is the reason there is no linter checks for this PR. Kindly follow through this instruction to see how to set it up - [ror-social-scaffold](https://github.com/microverseinc/ror-social-scaffold).

- [x] Your unit test does not work on my local computer. It keeps giving me this error - `cannot load such file -- rspec/core/profiler (LoadError)`. I will run it on another PC to see if the problem is on my side or not. But I'll appreciate it if you run the test again to make sure it runs fine on your PC before requesting another review.

- [x] Lastly, it will be nice if you update your README to reflect the features and changes you implemented in this milestone, like the project description section and how to setup/install your project and test run sections.

---

### After implementing the changes above, you can request for another code review.

---

Should you have any question, do reach out to me on Slack with the username - @adaorachi

Happy Coding :relaxed: 

MaryAnn Chukwuka.

**Comment by epinczinger** [comment]
HI @adaorachi, thanks for your review.

I've done the requested changes. In order to run tests, you should type the following command, works perfectly on my computer.

 ```Ruby
    rspec --format documentation 
```

Submitting for another code review. Thanks

**Review by rOluochKe — APPROVED** [review]
Hello @epinczinger 
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
